project:
  type: website
  output-dir: "docs/"

website:
  title: "Blog do Arthur Boari"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/arthurboari
      - text: "{{< fa brands researchgate >}}"
        href: https://www.researchgate.net/profile/Arthur-Boari
      - text: "{{< fa brands kaggle >}}"
        href: https://www.kaggle.com/arthurboari
      - icon: linkedin
        href: https://www.linkedin.com/in/arthurboari/
format:
  html:
    theme:
      dark: journal
      light: cosmo
    css: styles.css
lang: pt-br
editor: visual

