project:
  type: website
  output-dir: "docs/"

website:
  title: "Blog do Arthur Boari"
  body-footer: Blog feito em [Quarto](https://quarto.org/), por Arthur Boari.
  navbar:
    left:
      - text: "Cursos"
        href: courses.html
    right:
      - about.qmd
      - icon: github
        href: https://github.com/arthurboari
      - text: "{{< fa brands researchgate >}}"
        href: https://www.researchgate.net/profile/Arthur-Boari
      - text: "{{< fa brands kaggle >}}"
        href: https://www.kaggle.com/arthurboari
      - icon: linkedin
        href: https://www.linkedin.com/in/arthurboari/
format:
  html:
    highlight-style: a11y
    theme:
      dark: journal
      light: morph
    css: styles.css
lang: pt-br
editor: visual

